### ISSUE TITLE
"ImageMagick is not installed" error

### ISSUE THREAD

**Issue by thrnd** [courtneypattison/gulp-jpeg-2000#4]
Hi there!

I wanted to try your package, but some weird error happened. I have both ImageMagick and GraphicsMagick installed (`magick` / `gm` commands in cmd/git bash works) but your package errores with `ImageMagick is not installed! Installation instructions: https://github.com/courtneypattison/gulp-jpeg-2000` message.

I'm using gulp 4.0.2 and latest IM release. OS is windows 10.

Can you help me with solution to this error?

**Comment by courtneypattison** [comment]
@thrnd Thank you so much for letting me know! I think the problem was that I was using a shortcut to check for the ImageMagick install that you may be using for something else: `$convert -version`. Could you pretty please check to see if it is working now with v1.1.3 and report back? Thanks again!

**Comment by thrnd** [comment]
Ok. Now it has `Stream yields empty buffer` error =)

**Comment by courtneypattison** [comment]
Of course it couldn't be that easy! Looking into the problem a bit more, it seems like ImageMagick [overhauled its command-line tools from version 6 to 7](https://imagemagick.org/script/porting.php). This plugin is really just a thin wrapper over [gulp-gm](https://www.npmjs.com/package/gulp-gm). Since it's primarily maintained for GraphicsMagick, I think maybe they haven't updated the commands for ImageMagick. I used ImageMagick instead of GraphicsMagick for this plugin because JP2 is included automatically, whereas, with GraphicsMagick you need an additional package. gulp-jpeg-2000 plugin is still working for me on my Mac with ImageMagick 7.0.10. My extremely speculative guess is that the symbolic link for `$convert` to `$magick` isn't working on your computer. If it's not too much to ask, could you please try gulp-gm with ImageMagick enabled and see if works for you? `{return gm.setFormat('jp2'); }, {imageMagick: true}` Thank you!

**Comment by thrnd** [comment]
So... yep. The problem was that i didn't check "install legacy tools" in IM installer => i didn't have `convert` command in my CMD (is it called symlink?).

Now it works fine. Thank you.

I guess you can now note this case in your README =)

**Comment by courtneypattison** [comment]
Yay! I'm happy you got it working. I'll definitely update the README and fix up the error message a bit. Thank you for all your help!
